/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Uri struct {
	RawAuthority string `json:"rawAuthority,omitempty"`
	Fragment string `json:"fragment,omitempty"`
	Query string `json:"query,omitempty"`
	RawFragment string `json:"rawFragment,omitempty"`
	RawSchemeSpecificPart string `json:"rawSchemeSpecificPart,omitempty"`
	Opaque bool `json:"opaque,omitempty"`
	Port int32 `json:"port,omitempty"`
	Path string `json:"path,omitempty"`
	RawPath string `json:"rawPath,omitempty"`
	RawUserInfo string `json:"rawUserInfo,omitempty"`
	Absolute bool `json:"absolute,omitempty"`
	Scheme string `json:"scheme,omitempty"`
	Host string `json:"host,omitempty"`
	UserInfo string `json:"userInfo,omitempty"`
	Authority string `json:"authority,omitempty"`
	RawQuery string `json:"rawQuery,omitempty"`
	SchemeSpecificPart string `json:"schemeSpecificPart,omitempty"`
}
